# Generated by Django 3.1 on 2020-08-19 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Nazwa')),
                ('ingredients', models.TextField(verbose_name='Składniki')),
                ('description', models.TextField(verbose_name='Opis')),
                ('created', models.DateField(auto_now_add=True, verbose_name='Stworzone')),
                ('updated', models.DateField(auto_now_add=True, verbose_name='Zaktualizowane')),
                ('preparation_time', models.PositiveIntegerField(verbose_name='Czas przygotowania')),
                ('votes', models.PositiveIntegerField(default=0, verbose_name='Głosy')),
            ],
        ),
    ]
