# Generated by Django 3.1 on 2020-08-20 06:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_meal_schedule', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DayName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('pn', 'Poniedziałek'), ('wt', 'Wtorek'), ('śr', 'Środa'), ('cz', 'Czwartek'), ('pt', 'Piątek'), ('so', 'Sobota'), ('ni', 'Niedziela')], default='pn', max_length=2, verbose_name='Dzień')),
                ('order', models.TextField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Nazwa')),
                ('description', models.TextField(verbose_name='Opis')),
                ('created_data', models.DateField(auto_now_add=True, verbose_name='Stworzone')),
            ],
        ),
        migrations.CreateModel(
            name='RecipePlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meal_name', models.TextField()),
                ('order', models.TextField(unique=True)),
                ('DayName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_meal_schedule.dayname')),
                ('Plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_meal_schedule.plan')),
                ('Recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_meal_schedule.recipe')),
            ],
        ),
        migrations.AddField(
            model_name='plan',
            name='recipes',
            field=models.ManyToManyField(through='app_meal_schedule.RecipePlan', to='app_meal_schedule.Recipe'),
        ),
    ]
