# Generated by Django 3.1 on 2020-08-23 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_meal_schedule', '0002_auto_20200820_0629'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='preparation_method',
            field=models.TextField(null=True, verbose_name='Sposób przygotowania'),
        ),
    ]
